name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          driver-opts: |
            image=moby/buildkit:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current date and time
        id: date
        run: echo "DATE_TAG=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      # 添加缓存元数据步骤
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/offensive-docker-kali
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/offensive-docker-kali:${{ env.DATE_TAG }}
            ${{ secrets.DOCKER_USERNAME }}/offensive-docker-kali:latest
          cache-from: |
            type=registry,ref=${{ secrets.DOCKER_USERNAME }}/offensive-docker-kali:latest
            type=gha
          cache-to: |
            type=inline
            type=gha,mode=max
          platforms: linux/amd64
          provenance: false
          outputs: type=registry,compression=zstd,compression-level=3